# Project language
language: php

# Allows use container-based infrastructure
sudo: false

# Cache composer packages so "composer install" is faster
cache:
  directories:
    - $HOME/.composer/cache/files


# Matrix to test in every php version
matrix:
  # Fast finish allows to set the build as "finished" even if the "allow_failures" matrix elements are not finished yet.
  fast_finish: true
  include:
    - php: 7.1
    - php: 7.2
    - php: hhvm
  allow_failures:
    - php: hhvm

# Define an environment variable
env:
  - SYMFONY_VERSION="4.0.*" DB=pgsql


# Install composer dependencies,
# Create database, schema and fixtures
install:
  - composer install
  - cp app/config/parameters.yml.dist app/config/parameters.yml
  - php bin/console cache:clear --no-warmup

# Run script
script:
  - phpunit