index:
    path: /
    controller: App\Controller\DefaultController::index


api_login_check:
    path: /api/login_check

app_simple_api:
    path: /api/simple/number
    controller: App\Controller\SimpleAPIController::number

app_create_entity_api:
    path: /api/create/{type}/{name}/{description}/{projectId}
    controller: App\Controller\SimpleAPIController::create
    requirements:
        type: 'Project|Task'
    defaults:   { projectId: null, description: null }

app_update_entity_api:
    path: /api/update/{type}/{entityId}/{name}/{description}/{projectId}
    controller: App\Controller\SimpleAPIController::update
    requirements:
        type: 'Project|Task'
        entityId: \d+
    defaults:   { projectId: null, description: null }

app_remove_entity_api:
    path: /api/remove/{type}/{entityId}
    controller: App\Controller\SimpleAPIController::remove
    requirements:
        type: 'Project|Task'
        entityId: \d+

app_list_entity_api:
    path: /api/list/{type}/{projectId}
    controller: App\Controller\SimpleAPIController::list
    requirements:
        type: 'Project|Task'
    defaults:   { projectId: null }

#fos user
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile